import { IRoute } from 'umi';
import { IBestAFSRoute } from '@umijs/plugin-layout';

const routes: IBestAFSRoute = [
  {
    path: '/',
    component: '@/layouts/BasicLayout',
    routes: [
      {
        path: '/',
        redirect: '/institution/hospital',
      },
      {
        path: 'institution',
        redirect: 'hospital',
      },
      {
        path: 'institution',
        name: 'institutionData',
        code: 'institution',
        breadcrumb: '机构管理',
        icon: 'dashboard',
        routes: [
          {
            path: 'hospital',
            component: '@/pages/institution/hospital',
            name: 'hospitalManage',
            code: 'hospitalManage',
            breadcrumb: '医院主数据',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/hospital',
                redirect: '/institution/hospital/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/hospital/list',
                name: 'hospitalList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/hospital',
              },
              {
                path: 'institutionImport',
                component: '@/pages/institution/hospital/institutionImport',
                breadcrumb: '医院导入',
                associatedHighLight: '/institution/hospital',
              },
              {
                path: 'aliasImport',
                component: '@/pages/institution/hospital/aliasImport',
                breadcrumb: '医院别名导入',
                associatedHighLight: '/institution/hospital',
              },
              {
                path: 'updateImport',
                component: '@/pages/institution/hospital/updateImport',
                breadcrumb: '更新医院导入',
                associatedHighLight: '/institution/hospital',
              },
              {
                path: 'subInstitutionImport',
                component: '@/pages/institution/hospital/subInstitutionImport',
                breadcrumb: '下级机构导入',
                associatedHighLight: '/institution/hospital',
              },
            ],
          },
          {
            path: 'pharmacy',
            component: '@/pages/institution/pharmacy',
            name: 'pharmacyManage',
            code: 'pharmacyManage',
            breadcrumb: '药店主数据',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/pharmacy',
                redirect: '/institution/pharmacy/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/pharmacy/list',
                name: 'pharmacyList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/pharmacy',
              },
              {
                path: 'institutionImport',
                component: '@/pages/institution/pharmacy/institutionImport',
                breadcrumb: '药店导入',
                associatedHighLight: '/institution/pharmacy',
              },
              {
                path: 'aliasImport',
                component: '@/pages/institution/pharmacy/aliasImport',
                breadcrumb: '药店别名导入',
                associatedHighLight: '/institution/pharmacy',
              },
              {
                path: 'updateImport',
                component: '@/pages/institution/pharmacy/updateImport',
                breadcrumb: '更新药店导入',
                associatedHighLight: '/institution/pharmacy',
              },
              {
                path: 'subInstitutionImport',
                component: '@/pages/institution/pharmacy/subInstitutionImport',
                breadcrumb: '下级机构导入',
                associatedHighLight: '/institution/pharmacy',
              },
            ],
          },
          {
            path: 'distributor',
            component: '@/pages/institution/distributor',
            name: 'dealerManage',
            code: 'dealerManage',
            breadcrumb: '经销商主数据',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/distributor',
                redirect: '/institution/distributor/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/distributor/list',
                name: 'distributorList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/distributor',
              },
              {
                path: 'institutionImport',
                component: '@/pages/institution/distributor/institutionImport',
                breadcrumb: '经销商导入',
                associatedHighLight: '/institution/distributor',
              },
              {
                path: 'aliasImport',
                component: '@/pages/institution/distributor/aliasImport',
                breadcrumb: '经销商别名导入',
                associatedHighLight: '/institution/distributor',
              },
              {
                path: 'levelImport',
                component: '@/pages/institution/distributor/levelImport',
                breadcrumb: '经销商级别导入',
                associatedHighLight: '/institution/distributor',
              },
              {
                path: 'updateImport',
                component: '@/pages/institution/distributor/updateImport',
                breadcrumb: '更新经销商导入',
                associatedHighLight: '/institution/distributor',
              },
              {
                path: 'contractImport',
                component: '@/pages/institution/distributor/contractImport',
                breadcrumb: '经销商协议导入',
                associatedHighLight: '/institution/distributor',
              },
            ],
          },
          {
            path: 'agent',
            name: 'agentManage',
            code: 'agentManage',
            breadcrumb: '代理商主数据',
            component: '@/pages/institution/agent/index',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/agent',
                redirect: '/institution/agent/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/agent/list',
                name: 'agentList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/agent',
              },
              {
                path: 'institutionImport',
                component: '@/pages/institution/agent/institutionImport',
                breadcrumb: '代理商导入',
                associatedHighLight: '/institution/agent',
              },
              {
                path: 'aliasImport',
                component: '@/pages/institution/agent/aliasImport',
                breadcrumb: '代理商别名导入',
                associatedHighLight: '/institution/agent',
              },
              {
                path: 'updateImport',
                component: '@/pages/institution/agent/updateImport',
                breadcrumb: '更新代理商导入',
                associatedHighLight: '/institution/agent',
              },
              {
                path: 'agentAgreeImport',
                component: '@/pages/institution/agent/agentAgreeImport',
                breadcrumb: '代理商协议导入',
                associatedHighLight: '/institution/agent',
              },
              {
                path: 'agreeContractImport',
                component: '@/pages/institution/agent/agreeContractImport',
                breadcrumb: '协议配送商导入',
                associatedHighLight: '/institution/agent',
              },
              {
                path: 'detail/:id',
                component: '@/pages/institution/agent/detail/index',
                name: 'agentDetail',
                breadcrumb: '详情',
                associatedHighLight: '/institution/agent',
                routes: [
                  {
                    path: 'terminal/:id',
                    component: '@/pages/institution/agent/terminal/index',
                    name: 'agentTerminal',
                    breadcrumb: false,
                    associatedHighLight: '/institution/agent',
                    routes: [
                      {
                        path: 'import',
                        component: '@/pages/institution/agent/terminal/import',
                        name: 'agentTerminalImport',
                        breadcrumb: false,
                        associatedHighLight: '/institution/agent',
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            path: 'other',
            component: '@/pages/institution/other',
            name: 'otherManage',
            code: 'otherManage',
            breadcrumb: '其他类型机构',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/other',
                redirect: '/institution/other/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/other/list',
                name: 'otherList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/other',
              },
              {
                path: 'institutionImport',
                component: '@/pages/institution/other/institutionImport',
                breadcrumb: '其他导入',
                associatedHighLight: '/institution/other',
              },
              {
                path: 'aliasImport',
                component: '@/pages/institution/other/aliasImport',
                breadcrumb: '其他别名导入',
                associatedHighLight: '/institution/other',
              },
              {
                path: 'updateImport',
                component: '@/pages/institution/other/updateImport',
                breadcrumb: '更新其他类型导入',
                associatedHighLight: '/institution/other',
              },
            ],
          },
          {
            path: 'search',
            component: '@/pages/institution/search',
            name: 'institutionSearch',
            code: 'institutionSearch',
            breadcrumb: '机构查询',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/search',
                redirect: '/institution/search/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/search/list',
                name: 'searchList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/search',
              },
              {
                path: 'institutionImport',
                component: '@/pages/institution/search/Import',
                breadcrumb: '机构导入',
                associatedHighLight: '/institution/search',
              },
            ],
          },
          {
            path: 'newApply',
            component: '@/pages/institution/newApply',
            name: 'institutionNewApply',
            code: 'institutionNewApply',
            breadcrumb: '机构新增申请列表',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/institution/newApply',
                redirect: '/institution/newApply/list',
              },
              {
                path: 'list',
                component: '@/pages/institution/newApply/list',
                name: 'newApplyList',
                breadcrumb: '列表',
                associatedHighLight: '/institution/newApply',
              },
            ],
          },
          {
            path: 'institutionRecord',
            component: '@/pages/institutionRecord/index',
            name: '机构备案',
            code: 'institutionRecord',
            breadcrumb: '机构备案',
          },
          {
            path: 'dataProcess',
            name: 'dataProcess',
            icon: 'dashboard',
            breadcrumb: '数据处理',
            code: 'dataProcess',
            routes: [
              {
                path: 'changeAttribute',
                name: 'changeAttribute',
                code: 'changeAttribute',
                component: '@/pages/dataProcess/changeAttribute',
                breadcrumb: '机构属性变更记录',
                routes: [
                  {
                    path: '/institution/dataProcess/changeAttribute',
                    redirect: '/institution/dataProcess/changeAttribute/list',
                  },
                  {
                    path: 'list',
                    hideInMenu: true,
                    component: '@/pages/dataProcess/changeAttribute/list',
                    breadcrumb: '列表',
                    associatedHighLight:
                      '/institution/dataProcess/changeAttribute',
                  },
                ],
              },
              {
                path: 'mergeRecord',
                name: 'mergeRecord',
                code: 'mergeRecord',
                component: '@/pages/dataProcess/mergeRecord',
                breadcrumb: '机构合并记录',
                routes: [
                  {
                    path: '/institution/dataProcess/mergeRecord',
                    redirect: '/institution/dataProcess/mergeRecord/list',
                  },
                  {
                    path: 'list',
                    hideInMenu: true,
                    component: '@/pages/dataProcess/mergeRecord/list',
                    breadcrumb: '列表',
                    associatedHighLight: '/institution/dataProcess/mergeRecord',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        path: '/institution/info/:id?',
        component: '@/pages/institution/info',
        hideInMenu: true,
        associatedHighLight: '/institution',
        code: 'institution',
      },
      {
        path: '/match',
        component: '@/pages/match/index',
        name: 'matchManage',
        icon: 'dashboard',
        code: 'match',
      },
      {
        path: '/match/detail/:id/:template',
        component: '@/pages/match/detail',
        hideInMenu: true,
        associatedHighLight: '/match',
        code: 'match',
      },
      {
        path: '/doctor',
        component: '@/pages/doctor/index',
        name: 'doctorManage',
        icon: 'dashboard',
        code: 'doctor',
      },
      {
        path: '/doctor/detail/:id',
        component: '@/pages/doctor/detail',
        hideInMenu: true,
        associatedHighLight: '/doctor',
        code: 'detail',
      },
      {
        path: 'product',
        name: 'productManage',
        icon: 'dashboard',
        breadcrumb: '产品管理',
        code: 'product',
        routes: [
          {
            path: 'productData',
            name: 'productData',
            code: 'productData',
            component: '@/pages/product/productData',
            breadcrumb: '产品主数据',
            routes: [
              {
                path: '/product/productData',
                redirect: '/product/productData/list',
              },
              {
                path: 'list',
                hideInMenu: true,
                component: '@/pages/product/productData/list',
                breadcrumb: '列表',
                associatedHighLight: '/product/productData',
              },
            ],
          },
          {
            path: 'price',
            name: 'price',
            breadcrumb: '价格管理',
            code: 'priceManage',
            routes: [
              // {
              //   name: 'secondNegotiation',
              //   path: 'secondNegotiation',
              //   component: '@/pages/product/PriceControl',
              //   breadcrumb: '二次议价',
              //   code: 'secondNegotiation',
              // },
              {
                path: 'provincePrice',
                name: 'provincePrice',
                breadcrumb: '省份价格',
                code: 'provincePrice',
                component: '@/pages/product/provincePrice',
                routes: [
                  {
                    path: '/product/price/provincePrice',
                    redirect: '/product/price/provincePrice/list',
                  },
                  {
                    path: 'list',
                    hideInMenu: true,
                    component: '@/pages/product/provincePrice/list',
                    breadcrumb: '列表',
                    associatedHighLight: '/product/price/provincePrice',
                  },
                  {
                    path: 'import',
                    hideInMenu: true,
                    component: '@/pages/product/provincePrice/import',
                    breadcrumb: '导入',
                    associatedHighLight: '/product/price/provincePrice',
                  },
                ],
              },
              {
                name: 'terminalPrice',
                path: 'terminalPrice',
                code: 'terminalPrice',
                breadcrumb: '经销商价格',
                component: '@/pages/product/terminalPrice',
                routes: [
                  {
                    path: '/product/price/terminalPrice',
                    redirect: '/product/price/terminalPrice/list',
                  },
                  {
                    path: 'list',
                    hideInMenu: true,
                    component: '@/pages/product/terminalPrice/list',
                    breadcrumb: '列表',
                    associatedHighLight: '/product/price/terminalPrice',
                  },
                  {
                    path: 'import',
                    hideInMenu: true,
                    component: '@/pages/product/terminalPrice/import',
                    breadcrumb: '导入',
                    associatedHighLight: '/product/price/terminalPrice',
                  },
                ],
              },
            ],
          },
          {
            path: 'import',
            hideInMenu: true,
            component: '@/pages/product/productData/import',
            breadcrumb: '产品导入',
            associatedHighLight: '/product/productData',
          },
          {
            path: 'batchNoImport',
            hideInMenu: true,
            component: '@/pages/product/productData/batchNoImport',
            breadcrumb: '批号导入',
            associatedHighLight: '/product/productData',
          },
        ],
      },
      {
        path: '/import',
        component: '@/pages/import/index',
        hideInMenu: true,
        associatedHighLight: '/import',
        code: 'import',
        breadcrumb: '导入',
      },
    ],
  },
];

export default routes as IRoute[];
