import transformText, { transformArray } from '@/utils/transform';
import { Select } from 'antd';
import ProTable, { ProColumns, ActionType } from '@ant-design/pro-table';

const { Option } = Select;

const valueEnum = {
  // QUALITY_SUCCESS: { text: '质检成功', status: 'QUALITY_SUCCESS' },
  // QUALITY_FAILURE: { text: '质检失败', status: 'QUALITY_FAILURE' },
  质检成功: { text: '质检成功', status: 'QUALITY_SUCCESS' },
  质检失败: { text: '质检失败', status: 'QUALITY_FAILURE' },
};

//月销售、日销售
export const columnsSDAndSM: any = () => {
  return [
    {
      title: '经销商名称',
      dataIndex: 'institutionName',
      valueType: 'text',
      hideInTable: true,
    },
    {
      title: '状态',
      // key: 'select',
      valueType: 'select',
      dataIndex: 'fileStatus',
      hideInTable: true,
      valueEnum,
    },
    {
      title: '销售表主键',
      dataIndex: 'sale_id',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '日期',
      dataIndex: 'sale_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '订单日期',
      dataIndex: 'order_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商代码',
      dataIndex: 'institution_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商名称',
      dataIndex: 'institution_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户代码',
      dataIndex: 'customer_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户名称',
      dataIndex: 'customer_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户省份',
      dataIndex: 'customer_province',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户城市',
      dataIndex: 'customer_city',
      valueType: 'text',
      hideInSearch: true,
    },
    // {
    //   title: '客户地址',
    //   dataIndex: 'productUnit',
    //   valueType: 'text',
    //   hideInSearch: true,
    // },
    {
      title: '产品代码',
      dataIndex: 'product_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品名称',
      dataIndex: 'product_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '通用名',
      dataIndex: 'general_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品规格',
      dataIndex: 'product_spec',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品批号',
      dataIndex: 'product_batch',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产日期',
      dataIndex: 'product_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '有效期',
      dataIndex: 'valid_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品型号',
      dataIndex: 'product_model',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品线',
      dataIndex: 'product_line',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '数量',
      dataIndex: 'quantity',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单位',
      dataIndex: 'product_unit',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单价',
      dataIndex: 'price',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '金额',
      dataIndex: 'amount',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产厂家',
      dataIndex: 'producer',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售行为',
      dataIndex: 'behavior',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售单号',
      dataIndex: 'sale_order',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '发运单',
      dataIndex: 'despatch_order',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '子公司名称',
      dataIndex: 'company_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '仓库',
      dataIndex: 'warehouse',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商名称',
      dataIndex: 'vendor_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '科室',
      dataIndex: 'department',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '开票日期',
      dataIndex: 'invoice_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '税额',
      dataIndex: 'tax_amount',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '物权',
      dataIndex: 'realm',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售成本',
      dataIndex: 'cost',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售备注',
      dataIndex: 'remark',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注1',
      dataIndex: 'remark_one',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注2',
      dataIndex: 'remark_two',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注3',
      dataIndex: 'remark_three',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注4',
      dataIndex: 'remark_four',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注5',
      dataIndex: 'remark_five',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注6',
      dataIndex: 'remark_six',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注7',
      dataIndex: 'remark_seven',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注8',
      dataIndex: 'remark_eight',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注9',
      dataIndex: 'remark_nine',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注10',
      dataIndex: 'remark_ten',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '所在行数',
      dataIndex: 'rowNum',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '状态',
      dataIndex: 'file_status',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '失败原因',
      dataIndex: 'failCause',
      valueType: 'text',
      hideInSearch: true,
    },
  ];
};

//月发货、日发货
export const columnsDDAndDM: any = () => {
  return [
    {
      title: '经销商名称',
      dataIndex: 'institutionName',
      valueType: 'text',
      hideInTable: true,
    },
    {
      title: '状态',
      // key: 'select',
      valueType: 'select',
      dataIndex: 'fileStatus',
      hideInTable: true,
      valueEnum,
    },
    {
      title: '销售表主键',
      dataIndex: 'sale_id',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '日期',
      dataIndex: 'sale_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '订单日期',
      dataIndex: 'order_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商代码',
      dataIndex: 'institution_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商名称',
      dataIndex: 'institution_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户代码',
      dataIndex: 'customer_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户名称',
      dataIndex: 'customer_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户省份',
      dataIndex: 'customer_province',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '客户城市',
      dataIndex: 'customer_city',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品代码',
      dataIndex: 'product_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品名称',
      dataIndex: 'product_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '通用名',
      dataIndex: 'general_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品规格',
      dataIndex: 'product_spec',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品批号',
      dataIndex: 'product_batch',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产日期',
      dataIndex: 'product_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '有效期',
      dataIndex: 'valid_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品型号',
      dataIndex: 'product_model',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品线',
      dataIndex: 'product_line',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '数量',
      dataIndex: 'quantity',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单位',
      dataIndex: 'product_unit',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单价',
      dataIndex: 'price',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '金额',
      dataIndex: 'amount',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产厂家',
      dataIndex: 'producer',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售行为',
      dataIndex: 'behavior',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售单号',
      dataIndex: 'sale_order',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '发运单',
      dataIndex: 'despatch_order',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '子公司名称',
      dataIndex: 'company_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '仓库',
      dataIndex: 'warehouse',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商名称',
      dataIndex: 'vendor_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '科室',
      dataIndex: 'department',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '开票日期',
      dataIndex: 'invoice_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '税额',
      dataIndex: 'tax_amount',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '物权',
      dataIndex: 'realm',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售成本',
      dataIndex: 'cost',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '销售备注',
      dataIndex: 'remark',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注1',
      dataIndex: 'remark_one',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注2',
      dataIndex: 'remark_two',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注3',
      dataIndex: 'remark_three',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注4',
      dataIndex: 'remark_four',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注5',
      dataIndex: 'remark_five',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注6',
      dataIndex: 'remark_six',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注7',
      dataIndex: 'remark_seven',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注8',
      dataIndex: 'remark_eight',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注9',
      dataIndex: 'remark_nine',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注10',
      dataIndex: 'remark_ten',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '所在行数',
      dataIndex: 'rowNum',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '状态',
      dataIndex: 'file_status',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '失败原因',
      dataIndex: 'failCause',
      valueType: 'text',
      hideInSearch: true,
    },
  ];
};

//月采购，日采购
export const columnsPDAndPM: any = () => {
  return [
    {
      title: '经销商名称',
      dataIndex: 'institutionName',
      valueType: 'text',
      hideInTable: true,
    },
    {
      title: '状态',
      // key: 'select',
      valueType: 'select',
      dataIndex: 'fileStatus',
      hideInTable: true,
      valueEnum,
    },
    {
      title: '采购表主键',
      dataIndex: 'purchase_id',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '日期',
      dataIndex: 'purchase_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '订单日期',
      dataIndex: 'order_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商代码',
      dataIndex: 'institution_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商名称',
      dataIndex: 'institution_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商代码',
      dataIndex: 'vendor_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商名称',
      dataIndex: 'vendor_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商省份',
      dataIndex: 'vendor_province',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商城市',
      dataIndex: 'vendor_city',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品代码',
      dataIndex: 'product_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品名称',
      dataIndex: 'product_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '通用名',
      dataIndex: 'general_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品规格',
      dataIndex: 'product_spec',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品批号',
      dataIndex: 'product_batch_code',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产日期',
      dataIndex: 'product_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '有效期',
      dataIndex: 'valid_date',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品型号',
      dataIndex: 'product_model',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品线',
      dataIndex: 'product_line',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '数量',
      dataIndex: 'quantity',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单位',
      dataIndex: 'product_unit',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单价',
      dataIndex: 'price',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '金额',
      dataIndex: 'amount',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产厂家',
      dataIndex: 'producer',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '采购行为',
      dataIndex: 'behavior',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '采购单号',
      dataIndex: 'purchase_order_num',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '进货单号',
      dataIndex: 'logistics_order_num',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '原厂发货清单',
      dataIndex: 'delivery_list',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '子公司名称',
      dataIndex: 'company_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '仓库',
      dataIndex: 'warehouse',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '物权',
      dataIndex: 'realm',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '采购备注',
      dataIndex: 'purchase_remark',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注1',
      dataIndex: 'remark_one',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注2',
      dataIndex: 'remark_two',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注3',
      dataIndex: 'remark_three',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注4',
      dataIndex: 'remark_four',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注5',
      dataIndex: 'remark_five',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注6',
      dataIndex: 'remark_six',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注7',
      dataIndex: 'remark_seven',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注8',
      dataIndex: 'remark_eight',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注9',
      dataIndex: 'remark_nine',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注10',
      dataIndex: 'remark_ten',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '所在行数',
      dataIndex: 'rowNum',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '状态',
      dataIndex: 'file_status',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '失败原因',
      dataIndex: 'failCause',
      valueType: 'text',
      hideInSearch: true,
    },
  ];
};

//月库存，日库存
export const columnsIDAndIM: any = () => {
  return [
    {
      title: '经销商名称',
      dataIndex: 'institutionName',
      valueType: 'text',
      hideInTable: true,
    },
    {
      title: '状态',
      // key: 'select',
      valueType: 'select',
      dataIndex: 'fileStatus',
      hideInTable: true,
      valueEnum,
    },
    {
      title: '库存表主键',
      dataIndex: 'inventoryId',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '日期',
      dataIndex: 'inventoryDate',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商代码',
      dataIndex: 'institutionCode',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '经销商名称',
      dataIndex: 'institutionName',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品代码',
      dataIndex: 'productCode',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品名称',
      dataIndex: 'productName',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '通用名',
      dataIndex: 'generalName',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品规格',
      dataIndex: 'productSpec',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品批号',
      dataIndex: 'productBatchCode',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产日期',
      dataIndex: 'productDate',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '有效期',
      dataIndex: 'validDate',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品型号',
      dataIndex: 'productModel',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '产品线',
      dataIndex: 'productLine',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '数量',
      dataIndex: 'quantity',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '可销数量',
      dataIndex: 'saleableQuantity',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '不可销数量',
      dataIndex: 'unsaleableQuantity',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单位',
      dataIndex: 'productUnit',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '单价',
      dataIndex: 'price',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '金额',
      dataIndex: 'amount',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '入库日期',
      dataIndex: 'warehouseDate',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '订单日期',
      dataIndex: 'orderDate',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '生产厂家',
      dataIndex: 'producer',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '库存状态',
      dataIndex: 'inventoryStatus',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '子公司名称',
      dataIndex: 'company_name',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '仓库',
      dataIndex: 'warehouse',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '供应商名称',
      dataIndex: 'supplierName',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '物权',
      dataIndex: 'realm',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注1',
      dataIndex: 'remark_one',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注2',
      dataIndex: 'remark_two',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注3',
      dataIndex: 'remark_three',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注4',
      dataIndex: 'remark_four',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注5',
      dataIndex: 'remark_five',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注6',
      dataIndex: 'remark_six',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注7',
      dataIndex: 'remark_seven',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注8',
      dataIndex: 'remark_eight',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注9',
      dataIndex: 'remark_nine',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '备注10',
      dataIndex: 'remark_ten',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '所在行数',
      dataIndex: 'rowNum',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '状态',
      dataIndex: 'file_status',
      valueType: 'text',
      hideInSearch: true,
    },
    {
      title: '失败原因',
      dataIndex: 'failCause',
      valueType: 'text',
      hideInSearch: true,
    },
  ];
};
